/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 96f14edaaebe10a1aaed675510441141)
interface __BaseEnv_Env {
	ASSETS: R2Bucket;
	ASSET_BASE_URL: "https://assets.launchloom.wrazyos.com";
	PLATFORM_ORIGINS: "https://launchloom-bhl.pages.dev,https://launchloom.wrazyos.com";
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	REVISION_COORDINATOR: DurableObjectNamespace<import("./worker/src/index").RevisionCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/index");
		durableNamespaces: "RevisionCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASSET_BASE_URL" | "PLATFORM_ORIGINS" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID">> {}
}
