/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 185f614504af5f0ff61bf1a5777bd278)
interface __BaseEnv_Env {
	ASSETS: R2Bucket;
	ASSET_BASE_URL: "https://assets.launchloom.wrazyos.com";
	PLATFORM_ORIGINS: "https://api.launchloom.wrazyos.com,https://launchloom-bhl.pages.dev,https://launchloom.wrazyos.com";
	REVISION_COORDINATOR: DurableObjectNamespace<import("./worker/src/index").RevisionCoordinator>;
	ONBOARDING_INVITES: DurableObjectNamespace<import("./worker/src/index").OnboardingInvites>;
	GENERATION_LEDGER: DurableObjectNamespace<import("./worker/src/index").GenerationLedger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/index");
		durableNamespaces: "RevisionCoordinator" | "OnboardingInvites" | "GenerationLedger";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASSET_BASE_URL" | "PLATFORM_ORIGINS">> {}
}
